---

modifyingUnitClasses:   # all ship movement was scaled up to larger numbers for fine tuning
  - id: harpoonship
    replace:
      moveRange: 9 # from 4
  - id: travelboat
    replace:
      moveRange: 16 # from 10
  - id: turtle
    replace:
      moveRange: 18 # from 12
  - id: warship
    replace:
      moveRange: 12 # from 8

...
