---

unitClasses:
  - id: travelboat_move_only
    name: unit_class_name_travelboat
    cost: 200
    movement: sailing
    moveRange: 6 
    damageMultiplier: 1
    aiPriority: 1.5
    weapons: []
    tags:
      - travelboat
      # - transport # think i need to turn this off to prevent loading
      - type.sea
    battleUnitCount: 1
    loadCapacity: 2
    transportTags: [ type.ground.light, type.ground.heavy, type.amphibious ]
    isHiddenInCutsceneEditor: true
    isHidden: true
    isRecruitable: false
    classIconSpritesheet: ui_GoWBalanceMod
    codexClass: travelboat
    appearsInLists: false
    inPalettes: false
    

units:
  - class: travelboat_move_only
    faction: cherrystone
    name: unit_name_travelboat_cherrystone
    mapAnimation: units/travelboat/cherrystone/map_travelboat_cherrystone
    battleAnimation: units/travelboat/cherrystone/battle_travelboat_cherrystone
    smallPortrait: units/travelboat/cherrystone/portrait_travelboat_cherrystone_small.png
    mediumPortrait: units/travelboat/cherrystone/portrait_travelboat_cherrystone.png
    mapSpeed: 6.0
    grabPos: [15, 15]
    deathMoveMin: 80
    deathMoveMax: 80
    sounds:
      attackMap: unitAttack
      attack: soldierAttackRed
      attackShout: soldierPreAttackRed
      death: shipDie
      deathMap: unitDie
      run: waterBoatEntry
      runMap: waterBoatEntry
      hit: hitWood
      hitMap: hitWood

  - class: travelboat
    faction: felheim
    name: unit_name_travelboat_felheim
    mapAnimation: units/travelboat/felheim/map_travelboat_felheim
    battleAnimation: units/travelboat/felheim/battle_travelboat_felheim
    smallPortrait: units/travelboat/felheim/portrait_travelboat_felheim_small.png
    mediumPortrait: units/travelboat/felheim/portrait_travelboat_felheim.png
    mapSpeed: 8.0
    grabPos: [15, 15]
    deathMoveMin: 80
    deathMoveMax: 80
    sounds:
      attackMap: unitAttack
      attack: soldierAttackRed
      attackShout: soldierPreAttackRed
      death: shipDie
      deathMap: unitDie
      run: waterBoatEntry
      runMap: waterBoatEntry
      hit: hitWood
      hitMap: hitWood

  - class: travelboat
    faction: heavensong
    name: unit_name_travelboat_heavensong
    mapAnimation: units/travelboat/heavensong/map_travelboat_heavensong
    battleAnimation: units/travelboat/heavensong/battle_travelboat_heavensong
    smallPortrait: units/travelboat/heavensong/portrait_travelboat_heavensong_small.png
    mediumPortrait: units/travelboat/heavensong/portrait_travelboat_heavensong.png
    mapSpeed: 6.0
    grabPos: [15, 15]
    deathMoveMin: 80
    deathMoveMax: 80
    sounds:
      attackMap: unitAttack
      attack: soldierAttackRed
      attackShout: soldierPreAttackRed
      death: shipDie
      deathMap: unitDie
      run: waterBoatEntry
      runMap: waterBoatEntry
      hit: hitWood
      hitMap: hitWood

  - class: travelboat
    faction: floran
    name: unit_name_travelboat_floran
    mapAnimation: units/travelboat/floran/map_travelboat_floran
    battleAnimation: units/travelboat/floran/battle_travelboat_floran
    smallPortrait: units/travelboat/floran/portrait_travelboat_floran_small.png
    mediumPortrait: units/travelboat/floran/portrait_travelboat_floran.png
    mapSpeed: 6.0
    grabPos: [15, 15]
    deathMoveMin: 80
    deathMoveMax: 80
    sounds:
      attackMap: unitAttack
      attack: soldierAttackRed
      attackShout: soldierPreAttackRed
      death: shipDie
      deathMap: unitDie
      run: waterBoatEntry
      runMap: waterBoatEntry
      hit: hitWood
      hitMap: hitWood

...
