---

aiProfiles:
  - id: defensive
    name: ai_profile_defensive
    attackLookAhead: 0
    captureLookAhead: 0
    captureBias: 0.7
    attackBias: 1.5
    braveryBonus: 0.0
    recklessness: 0.0
    moveBias: 0.3
    lookAheadBias: 0.5
    baseDoomPenalty: 100.0
    additionalDoomPenalty: 1000.0
    attackThreshold:
      commander: 0.25
      hq: 0.25
    strategicValue: {}

...
