---

biomes:
  - id: grass
    name: biome_name_grass
    severeWeather: rain
  - id: desert
    name: biome_name_desert
    severeWeather: sandstorm
  - id: ice
    name: biome_name_ice
    severeWeather: snow
  - id: volcano
    name: biome_name_volcano
    hidden: true
    severeWeather: ash

...