---

colours:
  grid_grass_move_range_mine: '#744A49'
  grid_grass_move_range_outline_mine: '#744A49'
  grid_grass_move_and_attack_range_mine: '#DFC686'
  grid_grass_move_and_attack_range_outline_mine: '#E9DEB8'
  grid_grass_attack_range_outline_mine: '#DFC686'
  grid_grass_move_range_theirs: '#744A49'
  grid_grass_move_range_outline_theirs: '#744A49'
  grid_grass_attack_range_outline_theirs: '#1D1C24'
  grid_grass_move_and_attack_range_theirs: '#1D1C24'
  grid_grass_move_and_attack_range_outline_theirs: '#1D1C24'
  grid_grass_attack_target: '#D71919'
  grid_grass_attack_target_outline: '#EB3232'
  grid_grass_target: '#07AB5E'
  grid_grass_target_outline: '#0CDE8A'
  grid_grass_heal_outline: '#FFFFFF'

  grid_desert_move_range_mine: '#7a6665'
  grid_desert_move_range_outline_mine: '#7a6665'
  grid_desert_move_and_attack_range_mine: '#dfdbc4'
  grid_desert_move_and_attack_range_outline_mine: '#dfdbc4'
  grid_desert_attack_range_outline_mine: '#dfdbc4'
  grid_desert_move_range_theirs: '#7a6665'
  grid_desert_move_range_outline_theirs: '#7a6665'
  grid_desert_attack_range_outline_theirs: '#1D1C24'
  grid_desert_move_and_attack_range_theirs: '#1D1C24'
  grid_desert_move_and_attack_range_outline_theirs: '#1D1C24'
  grid_desert_attack_target: '#D71919'
  grid_desert_attack_target_outline: '#EB3232'
  grid_desert_target: '#07AB5E'
  grid_desert_target_outline: '#0CDE8A'
  grid_desert_heal_outline: '#FFFFFF'

  grid_ice_move_range_mine: '#916868'
  grid_ice_move_range_outline_mine: '#916868'
  grid_ice_move_and_attack_range_mine: '#fee19b'
  grid_ice_move_and_attack_range_outline_mine: '#f7f4e6'
  grid_ice_attack_range_outline_mine: '#f7f4e6'
  grid_ice_move_range_theirs: '#916868'
  grid_ice_move_range_outline_theirs: '#916868'
  grid_ice_move_and_attack_range_theirs: '#1D1C24'
  grid_ice_move_and_attack_range_outline_theirs: '#1D1C24'
  grid_ice_attack_range_outline_theirs: '#1D1C24'
  grid_ice_attack_target: '#D71919'
  grid_ice_attack_target_outline: '#EB3232'
  grid_ice_target: '#07AB5E'
  grid_ice_target_outline: '#0CDE8A'
  grid_ice_heal_outline: '#FFFFFF'

  grid_volcano_move_range_mine: '#47202e'
  grid_volcano_move_range_outline_mine: '#47202e'
  grid_volcano_move_and_attack_range_mine: '#a5996b'
  grid_volcano_move_and_attack_range_outline_mine: '#d1c69d'
  grid_volcano_attack_range_outline_mine: '#d1c69d'
  grid_volcano_move_range_theirs: '#47202e'
  grid_volcano_move_range_outline_theirs: '#47202e'
  grid_volcano_move_and_attack_range_theirs: '#1D1C24'
  grid_volcano_move_and_attack_range_outline_theirs: '#1D1C24'
  grid_volcano_attack_range_outline_theirs: '#1D1C24'
  grid_volcano_attack_target: '#df4747'
  grid_volcano_attack_target_outline: '#EB3232'
  grid_volcano_target: '#07AB5E'
  grid_volcano_target_outline: '#0CDE8A'
  grid_volcano_heal_outline: '#FFFFFF'

  player_red: '#AA003F'
  player_blue: '#366eca'
  player_green: '#77aa08'
  player_yellow: '#c57d00'
  player_purple: '#8013c7'
  player_cyan: '#22928b'
  player_pink: '#bb00a5'
  player_orange: '#cf4d19'
  player_white: '#b7c8ba'
  player_black: '#503b5e'
  player_neutral: '#737288'

  player_lightest_red: '#F56C49'
  player_lightest_blue: '#62BEFF'
  player_lightest_green: '#CFDB56'
  player_lightest_yellow: '#FCF3C5'
  player_lightest_purple: '#EC7FE1'
  player_lightest_cyan: '#53F2CD'
  player_lightest_pink: '#FF8D8B'
  player_lightest_orange: '#FFB24A'
  player_lightest_white: '#b7c8ba'
  player_lightest_black: '#776C92'
  player_lightest_neutral: '#C5C3D6'

  map_editor_location_red: '#ED1818'
  map_editor_location_yellow: '#E9E781'
  map_editor_location_green: '#76F379'
  map_editor_location_cyan: '#61DBE4'
  map_editor_location_blue: '#5C5CE9'
  map_editor_location_purple: '#A31AEC'
  map_editor_location_white: '#E6E6EC'
  map_editor_location_black: '#2E2530'
  map_editor_location_orange: '#F09F57'
  map_editor_location_pink: '#F892B8'
  map_editor_location_grey: '#7C7C9C'

  trigger_parameter_0: '#AE3023' #red
  trigger_parameter_1: '#2365AE' #blue
  trigger_parameter_2: '#8AB141' #green
  trigger_parameter_3: '#B141AE' #purple
  trigger_parameter_4: '#BEB834' #yellow
  trigger_parameter_5: '#668C85' #grey-green
  trigger_parameter_6: '#D773B9' #pink
  trigger_parameter_7: '#384047' #dark grey

  combat_overlay: '#0F143980'
  start_turn_overlay: '#000000C0'

  commander_death_overlay: '#FFFFFF'

  dialogue_text: '#623A34'
  dialogue_overlay: '#0F143980'

  ui_text: '#3D4265'
  ui_text_red: '#A91238'

  minimap_undefined: "#000000"

  minimap_grass_plains: '#8AB141'
  minimap_grass_forest: '#1B730D'
  minimap_grass_mountain: '#6B5C50'
  minimap_grass_road: '#E6DFAF'
  minimap_grass_bridge: '#BEB890'
  minimap_grass_river: '#488DD2'
  minimap_grass_beach: '#50C4CB'
  minimap_grass_sea: '#2365AE'
  minimap_grass_ocean: '#162D87'
  minimap_grass_reef: '#3B7DB8'
  minimap_grass_wall: '#40525B'
  minimap_grass_cobblestone: '#A4B1B7'
  minimap_grass_carpet: '#BC554E'

  minimap_desert_plains: '#D0A36A'
  minimap_desert_forest: '#1B730D'
  minimap_desert_mountain: '#6B5C50'
  minimap_desert_road: '#E6DFAF'
  minimap_desert_bridge: '#BEB890'
  minimap_desert_river: '#488DD2'
  minimap_desert_beach: '#50C4CB'
  minimap_desert_sea: '#2365AE'
  minimap_desert_ocean: '#162D87'
  minimap_desert_reef: '#3B7DB8'
  minimap_desert_wall: '#66554E'
  minimap_desert_cobblestone: '#D0C095'
  minimap_desert_carpet: '#D28D55'

  minimap_ice_plains: '#D0E1F4'
  minimap_ice_forest: '#156A53'
  minimap_ice_mountain: '#6B5C50'
  minimap_ice_road: '#E6DFAF'
  minimap_ice_bridge: '#BEB890'
  minimap_ice_river: '#488DD2'
  minimap_ice_beach: '#50C4CB'
  minimap_ice_sea: '#2365AE'
  minimap_ice_ocean: '#162D87'
  minimap_ice_reef: '#3B7DB8'
  minimap_ice_wall: '#3D4A5C'
  minimap_ice_cobblestone: '#A5b9CA'
  minimap_ice_carpet: '#6C7AB7'

  cutscene_fade_black: '#000000'
  cutscene_fade_white: '#FFFFFF'
  
  select_game_list_player_red: '#AA003F'
  select_game_list_player_blue: '#366eca'
  select_game_list_player_green: '#77aa08'
  select_game_list_player_yellow: '#c57d00'
  select_game_list_player_purple: '#8013c7'
  select_game_list_player_cyan: '#22928b'
  select_game_list_player_pink: '#bb00a5'
  select_game_list_player_orange: '#cf4d19'
  select_game_list_player_white: '#b7c8ba'
  select_game_list_player_black: '#503b5e'
  select_game_list_player_not_ready: '#737288'
  select_game_list_player_eliminated: '#737288'
  select_game_list_player_text_red: '#FFFFFF'
  select_game_list_player_text_blue: '#FFFFFF'
  select_game_list_player_text_green: '#FFFFFF'
  select_game_list_player_text_yellow: '#FFFFFF'
  select_game_list_player_text_purple: '#FFFFFF'
  select_game_list_player_text_cyan: '#FFFFFF'
  select_game_list_player_text_pink: '#FFFFFF'
  select_game_list_player_text_orange: '#FFFFFF'
  select_game_list_player_text_white: '#FFFFFF'
  select_game_list_player_text_black: '#FFFFFF'
  select_game_list_player_text_not_ready: '#FFFFFF'
  select_game_list_player_text_eliminated: '#FFFFFF'

  unit_icon_effective_tier0: "#77AA08"
  unit_icon_effective_tier1: "#20918B"
  unit_icon_effective_tier2: "#335EB0"
  unit_icon_vulnerable_tier0: "#AA003F"
  unit_icon_vulnerable_tier1: "#CD4C18"
  unit_icon_vulnerable_tier2: "#AC6722"
  unit_icon_recruit: "#335EB0"

...
