---
tilesets:
  - id: sky
    primaryConnect: []
    biomes:
      - types: [grass, desert, ice, volcano]
        battleBackgroundSpriteSheet: backgrounds/battlescreen_extendedbackgrounds
        battleBackgroundSprite: battlescreen_extendedbackgrounds_sky
        battleBackgroundSpriteForeground: battlescreen_extendedbackgrounds_sky_foreground
        iconSpriteSheet: ui
        iconSprite: terrain_icons_sky
...
